services:
  quickglimpse:
    build: .
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    environment:
      QUICKGLIMPSE_DATA_DIR: ${QUICKGLIMPSE_DATA_DIR}
      QUICKGLIMPSE_DB_PATH: ${QUICKGLIMPSE_DB_PATH}
    volumes:
      - quickglimpse-data:${QUICKGLIMPSE_DATA_DIR}
volumes:
  quickglimpse-data:
